test.pas:
build:
	fpc -Cr -FEbinary test.pas
	fpc -Cr -FEbinary reverse-list.pas
	fpc -Cr -FEbinary aufgabe-2.pas


run-test:
	./binary/test

run-reverse-list:
	./binary/reverse-list

run-aufgabe-2:
	./binary/aufgabe-2
