test.pas:
build:
	fpc -Cr -FEbinary aufgabe-2.pas
	fpc -Cr -FEbinary aufgabe-3.pas
	fpc -Cr -FEbinary aufgabe-4.pas

run-aufgabe-2:
	./binary/aufgabe-2

run-aufgabe-3:
	./binary/aufgabe-3

run-aufgabe-4:
	./binary/aufgabe-4
